.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. yescoin_qt test_yescoin_qt
clean: FORCE
	$(MAKE) -C .. yescoin_qt_clean test_yescoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_yescoin_qt_check
yescoin-qt yescoin-qt.exe: FORCE
	 $(MAKE) -C .. yescoin_qt
